version: '3.8'

services:
  backend:
    build:
      context: ./backend
      dockerfile: Dockerfile
    ports:
      - "3030:3030"
    environment:
      - NODE_ENV=production
      - PORT=3030
      - DATABASE_URL=mongodb://mongo:27017/easy-generator
      - JWT_SECRET=your_jwt_secret
      - REFRESH_TOKEN_SECRET=your_refresh_token_secret
    depends_on:
      - mongo

  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile
    ports:
      - "3031:3031"
    environment:
      - NEXT_PUBLIC_API_URL=http://backend:3030
    depends_on:
      - backend

  mongo:
    image: mongo:latest
    ports:
      - "27017:27017"
    volumes:
      - mongodb_data:/data/db

volumes:
  mongodb_data:
